camera:
    resolution: 1080
    frame_rate: 30
    device: 0
    exposure: auto

serial_port:
    path: /dev/pts/8
    baudrate: 115200
    stopbits: 1
    bytesize: 8
    parity: n
    timeout: 0.1

thread:
    frame: 1
    discern: 1
    queue_size: 5

# armour color [0:red 1:blue]
armour_color: 1